### ISSUE TITLE
Cant render scene with cornell box and pipapica rendered wrong

### ISSUE THREAD

**Issue by tigrazone** [SaschaWillems/VulkanPathTracer#2]
Why when I change sceneIndex to 0 cornelBox scene dont load and
PathTracer fails without messages?
When I change sceneIndex to 2, picapica scene have blue color
everywhere tint. picapica scene I get from
[https://github.com/h3r2tic/rtoy-samples/tree/main/assets/meshes](https://github.com/h3r2tic/rtoy-samples/tree/main/assets/meshes) and
create folder picapica and copy data from downloaded to created
folder. 
![Attachment](http://moo.ho.ua/picapica-wrong-image.png)

**Comment by SaschaWillems** [comment]
Can you please add some details? Do you get any error messages or validation layer messages? Cornel Box works fine for me, Pica Pica is unsupported. I'm using a slightly modified version.

Please note that this is a personal project and there is no guarantee for it to work 100%.

**Comment by tigrazone** [comment]
Can you publish your version of picapica and where from it can be downloaded?
