### ISSUE TITLE
Ivy sponza

### ISSUE THREAD

**Issue by tigrazone** [SaschaWillems/VulkanPathTracer#4]
Hello!
Where from I can load ivy sponza scene?
Did you change somehow scene from Intel repo?

**Comment by SaschaWillems** [comment]
You can get the scene from here: https://www.intel.com/content/www/us/en/developer/topic-technology/graphics-research/samples.html

It's split into multiple parts and loaded as multiple parts, see https://github.com/SaschaWillems/VulkanPathTracer/blob/master/src/main.cpp#L641.

Note that the scenes are very taxing, esp. the base scene with the 4k x 4k textures. So if you're running into out of memory problems, you may need to scale down the textures before loading the scenes. You can easily do that with https://gltf-transform.donmccurdy.com/cli.html.

**Comment by tigrazone** [comment]
and rename new_sponza/NewSponza_Main_Blender_glTF.gltf to new_sponza/NewSponza_Main_Blender_glTF_sm.gltf
or change src/main.cpp line 641 to
		models[0].loadFromFile(getAssetPath() + "models/new_sponza/NewSponza_Main_Blender_glTF.gltf", vulkanDevice, queue, glTFLoadingFlags);

Also I find typo error src/main.cpp line 617
models[1] rewrite as models[0]

**Comment by SaschaWillems** [comment]
yes, either change the gltf file name or change the code to use a different file name.

I'll take a look at the typo, but note that this is a personal playground and not guaranteed to always be in a working state.

**Comment by tigrazone** [comment]
Thanks for fixing!
