### ISSUE TITLE
unused parameters

### ISSUE THREAD

**Issue by tigrazone** [SaschaWillems/VulkanPathTracer#5]
Hello!
How used joint0 and weight0 parameters in struct Vertex in shaders?
If not used, how you plan to use these parameters?

**Comment by SaschaWillems** [comment]
Joints and weights are used for vertex skinning and animation. I don't plan on adding that to this personal toy project. If you're interested in how those are used, check out https://github.com/SaschaWillems/Vulkan-glTF-PBR
