### ISSUE TITLE
Depth stencil not used?

### ISSUE THREAD

**Issue by tigrazone** [SaschaWillems/VulkanPathTracer#6]
Seems depth stencil come from another project.
Is it not used in path tracer?
Can it be removed?

**Comment by SaschaWillems** [comment]
Can you elaborate? Are you talking about the depth stencil attachment?

**Comment by tigrazone** [comment]
I'm about depth stencil in path tracer. I think it can be removed because in path tracer is not used. I'm right?

**Comment by SaschaWillems** [comment]
Yes, the path tracing part does not required depth and/or stencil as it just dispatches to an image.
