### ISSUE TITLE
Could not creat Vulkan device

### ISSUE THREAD

**Issue by generalgaowei** [SaschaWillems/VulkanPathTracer#7]
In the last step, I got the error, 

Could not creat Vulkan device: ERROR_EXTENSION_NOT_PRESENT.

The amd radeon gpu card doesn't support the Vulkan funtions. Is that the reason?

**Comment by SaschaWillems** [comment]
What GPU?

**Comment by generalgaowei** [comment]
Nvidia Geforce MX330. Prof. Willems, Thanks for your reply.

**Comment by SaschaWillems** [comment]
That's a very very old GPU. And it simply does not support the hardware ray tracing extensions.
